name: omegat
version: 3.6.0~2.0
confinement: strict
architectures:
  - amd64
epoch: 0
icon: setup/gui/omegat.svg
license: setup/jre-COPYRIGHT
license-agreement: explicit

summary: OmegaT, the free (GPL) translation memory tool
description: |
  OmegaT is a free translation memory application written in Java.
  It is a tool intended for professional translators. It does not translate
  for you! (Software that does this is called "machine translation", and you
  will have to look elsewhere for it.)

apps:
  omegat:
    command: desktop-launch omegat
    plugs: [home, network, unity7]

parts:
  omegat:
    plugin: copy
    source: 'https://sourceforge.net/projects/omegat/files/OmegaT - Latest/OmegaT 3.6.0 update 2/OmegaT_3.6.0_02_Beta_Linux_64.tar.bz2'
    files:
      .: .
    snap:
      - OmegaT
      - OmegaT.jar
      - jre
      - docs
      - images
      - lib
      - plugins
      - scripts
    after:
      - desktop/gtk2
  runtime:
    plugin: nil
    stage-packages:
      - hunspell
      - hunspell-fr-comprehensive
      - hunspell-cs
      - libxtst6
  launcher:
    plugin: copy
    files:
      omegat.wrapper: bin/omegat
