name: omegat-cat
version: 4.1.5.3
confinement: strict
epoch: 0
grade: stable

summary: OmegaT, the free (GPL) translation memory tool
description: |
  OmegaT is a free translation memory application written in Java.
  It is a tool intended for professional translators. It does not translate
  for you! (Software that does this is called "machine translation", and you
  will have to look elsewhere for it.)

apps:
  omegat:
    command: desktop-launch omegat
    plugs: [home, network, desktop, wayland, desktop-legacy, x11]

plugs:
    gnome-3-26-1604:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-26-1604:gnome-3-26-1604
    gtk-3-themes:
      interface: content
      target: $SNAP/data-dir/themes
      default-provider: gtk-common-themes:gtk-3-themes
    icon-themes:
      interface: content
      target: $SNAP/data-dir/icons
      default-provider: gtk-common-themes:icon-themes
    sound-themes:
      interface: content
      target: $SNAP/data-dir/sounds
      default-provider: gtk-common-themes:sounds-themes

environment:
    XDG_DATA_DIRS: $SNAP/data-dir:$XDG_DATA_DIRS

parts:
  omegat:
    plugin: dump
    source: https://sourceforge.net/projects/omegat/files/OmegaT%20-%20Latest/OmegaT%204.1.5%20update%203/OmegaT_4.1.5_03_Beta_Without_JRE.zip
    prime:
      - OmegaT
      - OmegaT.jar
      - docs
      - images
      - lib
      - plugins
      - scripts
    organize:
      OmegaT_4.1.5_03_Beta_Without_JRE/OmegaT: OmegaT
      OmegaT_4.1.5_03_Beta_Without_JRE/OmegaT.jar: OmegaT.jar
      OmegaT_4.1.5_03_Beta_Without_JRE/docs: docs
      OmegaT_4.1.5_03_Beta_Without_JRE/images: images
      OmegaT_4.1.5_03_Beta_Without_JRE/lib: lib
      OmegaT_4.1.5_03_Beta_Without_JRE/plugins: plugins
      OmegaT_4.1.5_03_Beta_Without_JRE/scripts: scripts
    after:
      - runtime
    build-attributes:
      - no-system-libraries

  runtime:
    plugin: nil
    stage-packages:
      - default-jre
    after:
      - desktop-gnome-platform
    organize:
      usr/lib/jvm/java-*: usr/lib/jvm/java
    prime:
      - -var
      - -snap
      - -usr/include
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/gdb
      - -usr/share/lintian
      - -usr/share/man
      - -usr/lib/jvm/*/jre/lib/security/cacerts
      - -usr/lib/jvm/*/jre/docs
      - -usr/lib/jvm/*/man
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL -type l -name cacerts -delete
    build-attributes:
      - no-system-libraries

  launcher:
    plugin: dump
    source: launcher
    organize:
      omegat.wrapper: bin/omegat

  cacerts:
    plugin: dump
    source: cacerts
    organize:
      cacerts: usr/lib/jvm/java/jre/lib/security/cacerts

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
