name: omegat-cat
version: 4.1.0-1
confinement: strict
epoch: 0
grade: stable

summary: OmegaT, the free (GPL) translation memory tool
description: |
  OmegaT is a free translation memory application written in Java.
  It is a tool intended for professional translators. It does not translate
  for you! (Software that does this is called "machine translation", and you
  will have to look elsewhere for it.)

apps:
  omegat:
    command: desktop-launch omegat
    plugs: [home, network, unity7]

parts:
  omegat:
    plugin: dump
    source: http://sourceforge.net/projects/omegat/files/OmegaT%20-%20Latest/OmegaT%204.1.0/OmegaT_4.1.0_Beta_Without_JRE.zip
    snap:
      - OmegaT
      - OmegaT.jar
      - docs
      - images
      - lib
      - plugins
      - scripts
    organize:
      OmegaT_4.1.0_Beta_Without_JRE/OmegaT: OmegaT
      OmegaT_4.1.0_Beta_Without_JRE/OmegaT.jar: OmegaT.jar
      OmegaT_4.1.0_Beta_Without_JRE/docs: docs
      OmegaT_4.1.0_Beta_Without_JRE/images: images
      OmegaT_4.1.0_Beta_Without_JRE/lib: lib
      OmegaT_4.1.0_Beta_Without_JRE/plugins: plugins
      OmegaT_4.1.0_Beta_Without_JRE/scripts: scripts
    after:
      - desktop-gtk2
      - runtime

  runtime:
    plugin: nil
    stage-packages:
      - openjdk-8-jre
      - ca-certificates-java
      - fonts-dejavu-extra
    snap:
      - -var
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -usr/share/man
    stage:
      - -usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts

  launcher:
    plugin: dump
    source: launcher
    organize:
      omegat.wrapper: bin/omegat

  cacerts:
    plugin: dump
    source: cacerts
    organize:
      cacerts: usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/

  desktop-gtk2:
    snap:
      - -var
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -usr/share/man
