name: omegat-cat
version: 4.1.2.1-1
confinement: strict
epoch: 0
grade: stable

summary: OmegaT, the free (GPL) translation memory tool
description: |
  OmegaT is a free translation memory application written in Java.
  It is a tool intended for professional translators. It does not translate
  for you! (Software that does this is called "machine translation", and you
  will have to look elsewhere for it.)

apps:
  omegat:
    command: desktop-launch omegat
    plugs: [home, network, unity7]

plugs:
    gnome-3-24-platform:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-24:gnome-3-24-platform

parts:
  omegat:
    plugin: dump
    source: https://sourceforge.net/projects/omegat/files/OmegaT%20-%20Latest/OmegaT%204.1.2%20update%201/OmegaT_4.1.2_01_Beta_Without_JRE.zip
    prime:
      - OmegaT
      - OmegaT.jar
      - docs
      - images
      - lib
      - plugins
      - scripts
    organize:
      OmegaT_4.1.2_01_Beta_Without_JRE/OmegaT: OmegaT
      OmegaT_4.1.2_01_Beta_Without_JRE/OmegaT.jar: OmegaT.jar
      OmegaT_4.1.2_01_Beta_Without_JRE/docs: docs
      OmegaT_4.1.2_01_Beta_Without_JRE/images: images
      OmegaT_4.1.2_01_Beta_Without_JRE/lib: lib
      OmegaT_4.1.2_01_Beta_Without_JRE/plugins: plugins
      OmegaT_4.1.2_01_Beta_Without_JRE/scripts: scripts
    after:
      - runtime

  runtime:
    plugin: nil
    stage-packages:
      - openjdk-8-jre
      - gtk2-engines-pixbuf
      - libpng12-0
    after:
      - desktop-gnome-platform
    organize:
      usr/lib/jvm/java-8*: usr/lib/jvm/java
    prime:
      - -var
      - -snap
      - -usr/include
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/gdb
      - -usr/share/lintian
      - -usr/share/man
      - -usr/lib/jvm/*/jre/lib/security/cacerts
      - -usr/lib/jvm/*/jre/docs
      - -usr/lib/jvm/*/man
    install: |
      find $SNAPCRAFT_PART_INSTALL -type l -name cacerts -delete

  launcher:
    plugin: dump
    source: launcher
    organize:
      omegat.wrapper: bin/omegat

  cacerts:
    plugin: dump
    source: cacerts
    organize:
      cacerts: usr/lib/jvm/java/jre/lib/security/cacerts

  # https://bazaar.launchpad.net/~ubuntu-desktop/+junk/ghex-snap-gnome-3-24/view/head:/snapcraft.yaml
  desktop-gnome-platform:
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    source: https://github.com/kenvandine/snapcraft-desktop-helpers.git
    source-branch: gnome-3-24
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    stage-packages:
      - libgtk2.0-0
    prime:
      - "-*"
